apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hostname
spec:
  host: hostname
  subsets:
  - name: busy
    labels:
      status: busy
  - name: normal
    labels:
      status: normal
---
