#=====================================================================
#Hostname Service
#=====================================================================
apiVersion: v1
kind: Service
metadata:
  name: hostname-svc
  labels:
    app: hostname
    service: hostname
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: hostname
---
#=====================================================================
#Hostname Deployment
#=====================================================================
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostname-v2
  labels:
    app: hostname
    version: v2
spec:
  selector:
    matchLabels:
        app: hostname
        version: v2
  replicas: 3
  template:
    metadata:
      labels:
        app: hostname
        version: v2
        status: normal
    spec:
      containers:
      - name: hostname
        image: hostname:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
